# Generated by Django 5.2.17 on 2026-09-08 07:22

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='document_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
